tap "buo/cask-upgrade"
tap "homebrew/bundle"
brew "antidote"
brew "cask"
brew "curl"
brew "mas"
brew "pyenv"
brew "pyenv-virtualenv"
brew "wget"
cask "db-browser-for-sqlite"
cask "google-chrome"
cask "iterm2"
cask "notion"
cask "postman"
cask "slack"
cask "visual-studio-code"
cask "whatsapp"
mas "1Password 7", id: 1333542190
mas "Amphetamine", id: 937984704
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "KakaoTalk", id: 869223134
mas "Keynote", id: 409183694
mas "Magnet", id: 441258766
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
vscode "johnpapa.winteriscoming"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-toolsai.jupyter"
vscode "ms-toolsai.jupyter-keymap"
vscode "ms-toolsai.jupyter-renderers"
vscode "ms-toolsai.vscode-jupyter-cell-tags"
vscode "ms-toolsai.vscode-jupyter-slideshow"
