tap "buo/cask-upgrade"
tap "homebrew/bundle"
brew "antigen"
brew "cask"
brew "curl"
brew "mas"
brew "pyenv"
brew "pyenv-virtualenv"
brew "wget"
cask "google-chrome"
cask "iterm2"
cask "notion"
cask "slack"
cask "visual-studio-code"
mas "1Password 7", id: 1333542190
mas "Amphetamine", id: 937984704
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "KakaoTalk", id: 869223134
mas "Keynote", id: 409183694
mas "Magnet", id: 441258766
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
